# Generated by Django 3.1.5 on 2021-07-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210718_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_ratio', 'title']},
        ),
    ]
